### ISSUE TITLE
Discuss about regist user API

### ISSUE THREAD

**Issue by KAIYOHUGO** [mdcpp/mdoj#51]

**Comment by KAIYOHUGO** [comment]
With some offline discussion, we decide use the exists create user API. Frontend will need tweak config to show sign up UI

**Comment by KAIYOHUGO** [comment]
I think we can close this now. r? @Eason0729

**Comment by Eason0729** [comment]
Did we discussed?

**Comment by Eason0729** [comment]
there is a default_role option in config, when it's not presented or `none` is presented, we disallow registeration.

If a vaild role is presented(`user`, `super`), we allow registeration and set their role as the value?

**Comment by KAIYOHUGO** [comment]
> Did we discussed?

Yeah.... I remember it is on DC. 

> there is a default_role option in config, when it's not presented or `none` is presented, we disallow registeration.
> 
> If a vaild role is presented(`user`, `super`), we allow registeration and set their role as the value?

Yes, and frontend also have a config (`regist=true`) to set whether to show the signup UI.

**Comment by Eason0729** [comment]
I think we can close it now, and reopen if needed
