### ISSUE TITLE
Cannot add problem to another contest if problem has been in contest that deleted

### ISSUE THREAD

**Issue by Eason0729** [mdcpp/mdoj#65]
Cannot add problem to another contest if problem has been in contest that deleted

It doesn't happen if it's testcase, as the expect behavior for testcase is deleted if problem deleted.

**Comment by KAIYOHUGO** [comment]
@Eason0729 so we can close this now?

**Comment by Eason0729** [comment]
There is a commit on my fork attemping to solve this.

**Comment by Eason0729** [comment]
It should work, I will test it later to determine whether we should close the issue.

**Comment by Eason0729** [comment]
I just test it and it work.

~~Maybe we need some automatic testing~~

I will close this issue.
