### ISSUE TITLE
Relax the limit of testcase endpoint

### ISSUE THREAD

**Issue by KAIYOHUGO** [mdcpp/mdoj#82]
By default, tonic limit max decoding packet size at 4mb, but the limit of upload testcase is 8mb+8mb=16mb > 4mb

- [tonic](https://docs.rs/tonic/latest/tonic/server/struct.Grpc.html#method.max_decoding_message_size)

**Comment by Eason0729** [comment]
The upload limit is actually 16MB+16MB now.

Also, I would like to relax the limit only on that endpoint, but I don't see any way to do this on tonic(without using tower stuff)

**Comment by KAIYOHUGO** [comment]
> Also, I would like to relax the limit only on that endpoint, but I don't see any way to do this on tonic(without using tower stuff)

Yeah..., me too. Maybe is a good chance to learn tower (
This issue is only affect `tools` , lemme change `P-`

**Comment by Eason0729** [comment]
https://github.com/mdcpp/mdoj/pull/85

**Comment by Eason0729** [comment]
I actually find `tonic` providing builder option to change it without going low-level.
