### ISSUE TITLE
Fix `MyInfo`/`UserFullInfo` Werid Type

### ISSUE THREAD

**Issue by KAIYOHUGO** [mdcpp/mdoj#84]
MyInfo should not return `UserFullInfo`
https://github.com/mdcpp/mdoj/blob/4cc275f1053ce3f790fbe06dfb77b3b5af192576/grpc/proto/backend.proto#L794

`UserFullInfo` should not have `hashed_pwd` (This is origin from the old API design)
https://github.com/mdcpp/mdoj/blob/4cc275f1053ce3f790fbe06dfb77b3b5af192576/grpc/proto/backend.proto#L712-L716

**Comment by Eason0729** [comment]
https://github.com/mdcpp/mdoj/pull/85
